### ISSUE TITLE
README

### ISSUE THREAD

**Issue by jbrucker** [lunaticSKE12/GuessingGame#1]
Please write a better description of the program in README.md

don't put quotes around "# GuessingGame" because it prevents processing of Markdown tags.
the "#" is Markdown heading 1, like HTML <h1>.

**Comment by lunaticSKE12** [comment]
Edit README.md

**Comment by jbrucker** [comment]
You didn't fix the Markdown in README.  Did you bother to look at it in browser??

Closing the issue without fixing the problem cost you 1 pt on lab score.

**Comment by lunaticSKE12** [comment]
Sorry for mistake I forget to push next time I will check again before
closing issue
